@startuml
hide circle
skinparam linetype ortho

entity "user" {
  + id : INTEGER <<PK>>
  --
  username : VARCHAR(255) <<NN>>
  password : VARCHAR(255) <<NN>>
  picture : BYTEA
  admin : BOOLEAN <<NN>> <<default false>>
}

entity "amis" {
  + id_requestor : INTEGER <<PK>> <<FK>>
  + id_validator : INTEGER <<PK>> <<FK>>
}

entity "game_request" {
  + id_session : INTEGER <<PK>> <<FK>>
  + id_requestor : INTEGER <<PK>> <<FK>>
  + id_validator : INTEGER <<PK>> <<FK>>
  --
  datetime : TIMESTAMP <<NN>> <<default now()>>
}

entity "session" {
  + id : INTEGER <<PK>>
  --
  id_quiz : INTEGER <<NN>> <<FK>>
}

entity "quiz" {
  + id : INTEGER <<PK>>
  --
  nom : VARCHAR(255) <<NN>>
  picture : BYTEA
  private : BOOLEAN <<NN>> <<default true>>
  id_creator : INTEGER <<FK>>
}

entity "labelisable" {
  + id : INTEGER <<PK>>
}

entity "question" {
  + id : INTEGER <<PK>> <<FK>>
  --
  name : VARCHAR(255) <<NN>>
  id_answer : INTEGER <<FK>>
  grade : INTEGER
  picture : BYTEA
  duration : INTEGER
  id_creator : INTEGER <<FK>>
  private : BOOLEAN <<NN>> <<default true>>
}

entity "choice" {
  + id : INTEGER <<PK>>
  --
  content : VARCHAR(255) <<NN>>
  id_question : INTEGER <<NN>> <<FK>>
}

entity "answers" {
  + id : INTEGER <<PK>>
  --
  id_participation : INTEGER <<NN>> <<FK>>
  id_question : INTEGER <<NN>> <<FK>>
  id_decision : INTEGER <<NN>> <<FK>>
  duration : INTEGER
}

entity "comment" {
  + id_creator : INTEGER <<PK>> <<FK>>
  + id_quiz : INTEGER <<PK>> <<FK>>
  --
  message : VARCHAR(255) <<NN>>
  datetime : TIMESTAMP <<NN>>
}

entity "friend_request" {
  + id_requestor : INTEGER <<PK>> <<FK>>
  + id_validator : INTEGER <<PK>> <<FK>>
  --
  datetime : TIMESTAMP <<NN>> <<default now()>>
}

entity "grade" {
  + id_creator : INTEGER <<PK>> <<FK>>
  + id_labelisable : INTEGER <<PK>> <<FK>>
  --
  grade : DOUBLE PRECISION <<NN>> <<default 0>>
}

entity "label" {
  + id : INTEGER <<PK>>
  --
  nom : VARCHAR(255) <<NN>>
}

entity "modification_request" {
  + id_requestor : INTEGER <<PK>> <<FK>>
  + id_creator : INTEGER <<PK>> <<FK>>
  + id_question : INTEGER <<PK>> <<FK>>
  --
  message : VARCHAR(255) <<NN>>
  status : BOOLEAN <<NN>> <<default false>>
}

entity "nn_label_labelisable" {
  + id_label : INTEGER <<PK>> <<FK>>
  + id_labelisable : INTEGER <<PK>> <<FK>>
}

entity "nn_quiz_question" {
  + id_quiz : INTEGER <<PK>> <<FK>>
  + id_question : INTEGER <<PK>> <<FK>>
}

entity "participation" {
  + id : INTEGER <<PK>>
  --
  id_session : INTEGER <<NN>> <<FK>>
  id_user : INTEGER <<NN>> <<FK>>
  datetime : TIMESTAMP <<NN>> <<default now()>>
  score : INTEGER
}

' Relationships
user --o| amis : id_requestor
user --o| amis : id_validator
user --o| game_request : id_requestor
user --o| game_request : id_validator
user --o| comment : id_creator
user --o| friend_request : id_requestor
user --o| friend_request : id_validator
user --o| grade : id_creator
user --o| question : id_creator
user --o| quiz : id_creator
user --o| modification_request : id_requestor
user --o| modification_request : id_creator
user --o| participation : id_user

session --o| game_request : id_session
session --o| participation : id_session
quiz --o| session : id_quiz
quiz --o| comment : id_quiz
quiz --o| nn_quiz_question : id_quiz
labelisable --o| quiz : id
labelisable --o| question : id
labelisable --o| grade : id_labelisable
labelisable --o| nn_label_labelisable : id_labelisable

question --o| choice : id_question
question --o| answers : id_question
question --o| modification_request : id_question
question --o| nn_quiz_question : id_question
choice --o| answers : id_decision
choice --o| question : id_answer

participation --o| answers : id_participation

label --o| nn_label_labelisable : id_label

@enduml